### ISSUE TITLE
possible resolution for OpenAI-Version error

### ISSUE THREAD

**Issue by goldengrape** [whitead/paper-qa#100]
If you encounter the error:

openai.error.InvalidRequestError: Unsupported OpenAI-Version header provided: 2022-12-01. (HINT: you can provide any of the following supported versions: 2020-10-01, 2020-11-07. Alternatively, you can simply omit this header to use the default version associated with your account.)

This is a bug from langchain

https://github.com/hwchase17/langchain/issues/4154

For paperqa, a solution is that you can set api_version just before docs.query()
like 

```python 
openai.api_version = '2020-11-07'
docs.query('your question')
```
This bug does not appear locally on my computer, but when I deploy to streamlit cloud, it appears.

**Comment by whitead** [comment]
Should be fixed
