### ISSUE TITLE
RateLimitError on using paperqa with OpenAI API

### ISSUE THREAD

**Issue by anuvc** [whitead/paper-qa#101]
I'm trying to use `paperqa` for querying some papers. I got the `OPENAI_API_KEY` as instructed, however I'm running into the following error:
I've set `paperqa` to use `gpt-3.5` with `docs = Docs(llm='gpt-3.5-turbo')` 
```
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
```
What am I missing here? Do I need to necessarily a subscription with OPENAI to use their API key?

**Comment by nrasif** [comment]
yes, you need to pay the OpenAI API first
