### ISSUE TITLE
How to get all at once / how to abort generation?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [whitead/paper-qa#108]
With the advent of ChatGPT the typewriter style came into vogue again.

How do I get all text at once or stop generation of print(answer)?

**Comment by whitead** [comment]
This can be done by setting models via `docs.update_llms` where the models have enabled the stdout streaming documented in langchain.

**Comment by ErfolgreichCharismatisch** [comment]
Can you put that into an example?

**Comment by ErfolgreichCharismatisch** [comment]
> @ErfolgreichCharismatisch Did you get a solution to it? If yes, could you please share.

As he didn't reply, I abandoned the project.

**Comment by whitead** [comment]
Added example to README
