### ISSUE TITLE
why does Docs.__getstate__() save a local copy of doc_index and faiss_index in a predetermined index_path?

### ISSUE THREAD

**Issue by maspotts** [whitead/paper-qa#111]
Thanks so much for this project: it's really great!  I do have one source of confusion: I don't understand why the `Docs` class saves the doc index and faiss index into the `index_path` inside the `__getstate__()` method: as a result, when I execute `pickle.dump(index, file)`, I get another copy of the `doc_index`, from which a faiss index can be rebuilt when it's loaded: but why is `__getstate__()` saving its own copy of both `doc_index` and `faiss_index`?  (This actually bit me because I was building multiple indices, and noticed that the latest index was being used in queries, even if I loaded an earlier index (because I was originally allowing the indices to cache (via `__getstate__()`) in my home directory, and so subsequently created indices were overwriting earlier indices in that location.)

**Comment by whitead** [comment]
Should be fixed now

**Comment by maspotts** [comment]
I still the save_local() inside __getstate()__ in https://github.com/whitead/paper-qa/blob/main/paperqa/docs.py (or am I missing something?)

**Comment by whitead** [comment]
I think I misunderstood your question @maspotts. In this code:

```py
    def __getstate__(self):
        state = self.__dict__.copy()
        if self._faiss_index is not None:
            state["_faiss_index"].save_local(self.index_path)
        del state["_faiss_index"]
        del state["_doc_index"]
        return state
```

I only see the `_faiss_index` being saved. If you do not want it do be saved before pickling, just set it to `None`. `_doc_index` is never saved so I'm not sure how your problem can arise.

**Comment by whitead** [comment]
Now in v3, you can set `index_path` to `None` and it will not be saved
