### ISSUE TITLE
Getting a strange error when using ggml-model-q4_0.bin locally

### ISSUE THREAD

**Issue by LazyAIEnjoyer** [whitead/paper-qa#114]
ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: C:\ggml-model-q4_0.bin. Received error [WinError -529697949] Windows Error 0xe06d7363 (type=value_error)
  
Anyone that got a similar error?

**Comment by dgilbert002** [comment]
> ValidationError: 1 validation error for LlamaCpp **root** Could not load Llama model from path: C:\ggml-model-q4_0.bin. Received error [WinError -529697949] Windows Error 0xe06d7363 (type=value_error)
> 
> Anyone that got a similar error?

You had any luck, I have the same issue...

**Comment by sujitnoronha** [comment]
pip install llama-cpp-python==0.1.48 resolved the issue for me

**Comment by lechedanone** [comment]
pip install llama-cpp-python==0.1.53  resolved the issue for me
