### ISSUE TITLE
__setstate__ calls update_llm(None, None) which requires valid OpenAI API keys

### ISSUE THREAD

**Issue by GordonMcGregor** [whitead/paper-qa#122]
Project is excellent - thank you for releasing it.

When trying to use it with other LLMs, everything works via the docs.__init__ method, but after pickling, __setstate__ calls self.update_llm(None, None) which resets everything to OpenAI LLMs.  This requires a valid OpenAI key to validate, as llm is None, so you create instances of ChatOpenAi, which attempts to validate the OPENAI_API_KEY.

I can after, unpicking, call docs.update_llm() again with an instance of the LLM I want to use, but the current pickle /restore is still dependent on that ChatOpenAI instantiation in the first place.

I can hack around it by setting an invalid OpenAI key in the environment, but that's a bit of a kludge.

**Comment by whitead** [comment]
Thanks - check out version 1.9.0. Should be fixed

**Comment by GordonMcGregor** [comment]
works now. thank you.
