### ISSUE TITLE
is the OpenAI API key cached?

### ISSUE THREAD

**Issue by maspotts** [whitead/paper-qa#146]
I just noticed that an index that I had built using an older OpenAI API key was erroring out with "quota exceeded" each time I queried it: the key that I had used when I built it HAS used up its quota, but the key (via os.environ['OPENAI_API_KEY']) that I'm using at query time has not: and yet it seems to be using the old key (the one that was specified when the index was built).  I didn't see any obvious mechanism in the code (and no obvious cache files): is this expected behaviour?  Is there some explicit way to force paperqa to use the current value of os.environ['OPENAI_API_KEY'] when querying an existing index?  Thanks!

**Comment by whitead** [comment]
Yes, the new version pickles the LLM models which contain the openai key used when constructing the object. 

You can call `docs.update_llms('gpt-3.5-turbo')` (or whatever llm you want) to overwrite the existing llms after loading a paperqa object.

**Comment by maspotts** [comment]
Aha!  Of course!  I'm actually using that already, but it didn't occur to me to try it here!

So if I overwrite the existing llm then that will also overwrite the (saved) openai API key?

**Comment by maspotts** [comment]
Hmmm... what I actually want to do is to update the API key (from os.environ['OPENAI_API_KEY'] or as an explicit string, doesn't matter) but keep the existing llm (use the same model).  Is there an easy way to do that?

**Comment by whitead** [comment]
Yea, just do `docs.update_llms('gpt-4')`. Make sure you're on version 2 (since version 3 is incompatible with previously pickled docs)

**Comment by maspotts** [comment]
Ok but what if the index was previously built with a different LLM and I want to continue using the same LLM but just update the API token?MikeOn Jun 20, 2023, at 1:01 PM, Andrew White ***@***.***> wrote:﻿
Yea, just do docs.update_llms('gpt-4'). Make sure you're on version 2 (since version 3 is incompatible with previously pickled docs)
