### ISSUE TITLE
Elaborate on citations 

### ISSUE THREAD

**Issue by caretak3r** [whitead/paper-qa#16]
> To use paper-qa, you need to have a list of paths (valid extensions include: .pdf, .txt) and a list of citations (strings) that correspond to the paths. You can then use the Docs class to add the documents and then query them.

Just a bit confused on what `citations` means or how to provide the right input here. I see in your examples you provided citations like `WikiMedia Foundation, 2023, Accessed now`. 

Currently I have a scraper to grab PDFs from various sources based on a query ("vix volatility") and dump all PDFs into a dir labeled as such. 

Can you provide some other examples or how citations could be derived from various sources?

**Comment by whitead** [comment]
You could have the LLM generate the citation from the first chunk of text - would be a nice convenience function for the cost of a few tokens.

**Comment by whitead** [comment]
Ok, citations are now optional.
