### ISSUE TITLE
Migrate huggingface space functionality in?

### ISSUE THREAD

**Issue by xloem** [whitead/paper-qa#18]
I found https://huggingface.co/spaces/whitead/paper-qa, which is quite pleasant, but I'm having trouble reproducing the same functionality locally.

It would be nice to include its backend parts in the repository as a working example.

**Comment by whitead** [comment]
Of course - you can see the code [here](https://huggingface.co/spaces/whitead/paper-qa/blob/main/app.py)

**Comment by xloem** [comment]
Yes, I’m aware. I have had trouble reproducing it.
