### ISSUE TITLE
Does this work with Azure OpenAI?

### ISSUE THREAD

**Issue by theabhinavdas** [whitead/paper-qa#204]
Is it possible to use `paper-qa` with Azure OpenAI?

**Comment by filippo82** [comment]
As stated in the main [README of this repo](https://github.com/whitead/paper-qa#can-i-use-different-llms), you can use any LLM which is integrated with Langchain. Add yes [OpenAI on Azure](https://api.python.langchain.com/en/latest/llms/langchain.llms.openai.AzureOpenAI.html#langchain.llms.openai.AzureOpenAI) is one of those.

**Comment by theabhinavdas** [comment]
Cool, thanks!
