### ISSUE TITLE
Question regarding paper https://storage.googleapis.com/fh-public/paperqa/PaperQA__Retrieval_Augmented_Generative_Agent_for_Scientific_Research.pdf

### ISSUE THREAD

**Issue by sersoage** [whitead/paper-qa#221]
Does the current implementation support what is described in the paper?

**Comment by whitead** [comment]
Great question! This repo is missing the agent code, which we're working on adding soon.

**Comment by sersoage** [comment]
Thanks! Please let us know when updated. Keep up the good work
