### ISSUE TITLE
Segmentation error and unable to install simsimd

### ISSUE THREAD

**Issue by alexanderchang1** [whitead/paper-qa#239]
Hi,

I'm trying to setup a paperqa for my lab. However, simsimd isn't available for my institutional cluster due to a manylinux distribution error, and the numpy build-in for Langchain causes a segmentation error. Is there a possible workaround for this issue?

Best,
Alex

**Comment by whitead** [comment]
Do you need to use langchain? Langchain isn't required to use this package.

**Comment by alexanderchang1** [comment]
This was on the old v3 package. Closing accordingly.
