### ISSUE TITLE
'Docs' object has no attribute '_build_faiss_index'

### ISSUE THREAD

**Issue by carat64** [whitead/paper-qa#30]
Trying to run the huggingface app.py locally and see this error: 'Docs' object has no attribute '_build_faiss_index'

Tried to install faiss-cpu locally but doesn't fix the issue

It doesn't appear the uploaded papers are indexed as they are on the huggingface version; 
could this have something to do with the path of the gradio app?

**Comment by whitead** [comment]
Hi @carat64,

By default, `paperqa` locally creates a version and loads it on construction to cache the embeddings. This looks like it got cached before it had any docs. Can you delete the `.paperqa` directory that should be in your `$HOME/.paperqa`? Will work on detecting this though

**Comment by carat64** [comment]
@whitead Thanks!! got it running now.
