### ISSUE TITLE
how to "force" it to consider all papers?

### ISSUE THREAD

**Issue by nothingcomeseasy** [whitead/paper-qa#31]
hello! i'm loving this tool, thanks a lot for all the effort!

Do you guys have any tips on how to force the bot to consider all papers being passed to formulate the response? 

I notice that it randomly picks which paper it will respond to and others fall behind.

thanks!

**Comment by whitead** [comment]
It increases the cost, but you can increase `k` in the `query` function to consider more documents:

```py
docs.query("What manufacturing challenges are unique to bispecific antibodies?", k = 25)
```

If you have a very large bibliography, you can get a list of keywords to filter with first:

```py
generate_search_query("What manufacturing challenges are unique to bispecific antibodies?")
```

which will provide a few keyword searches that can be applied to pre-filter

**Comment by nothingcomeseasy** [comment]
thank you, I have the Open AI hard limit set so no worries about that :) 

Last question: I see that in the hugginface GUI you can also adjust the amount of words in answer, is there also an argument that I can pass in my prompt? didn't find it in readme and i'm not so used to python to find it in the code!

**Comment by jan-kubica** [comment]
Yes, @nothingcomeseasy , you can adjust the answer length using the `length_prompt` argument.

Example:
`docs.query("What manufacturing challenges are unique to bispecific antibodies?", length_prompt="about 200 words")`

**Comment by nothingcomeseasy** [comment]
sorry, but i'm still getting issues when I try to use number of papers > 3. Not sure what is wrong, but higher values of: **k**, **max_samples** and **length_prompt** don't seem to affect/improve the answers I get.

Also, it is citing the wrong authors for the papers (mixing in between).
