### ISSUE TITLE
Support other embeddings in Docs() method

### ISSUE THREAD

**Issue by recursionbane** [whitead/paper-qa#36]
Currently, both the llm and summary_llm can be customized in the Docs() object, but the Embeddings provider is not customizable.

Allowing the Docs() object to be initialized with an embeddings_model would allow paper-qa to be run fully locally.

**Comment by mtwomey** [comment]
Agree, I would love the option remove the dependency on OpenAI all together.

**Comment by whitead** [comment]
Fixed in #53
