### ISSUE TITLE
`Docs.add` not safe for using inside a `try-except`

### ISSUE THREAD

**Issue by MilesCranmer** [whitead/paper-qa#51]
Currently the README recommends using a `try-except` to skip over errors in adding to the `Docs()` object:

```py
for path, data in papers.items():
    try:
        docs.add(path)
    except ValueError as e:
        # sometimes this happens if PDFs aren't downloaded or readable
        print('Could not read', path, e)
```

#### Problem:

However, this is not safe as the `add` method of `Docs()` mutates its properties at different parts of the method:

```py
    def add(...):

        ...
            raise ValueError(f"Document {path} already in collection.")
        ...
                raise ValueError(
                    f"Could not parse key from citation {citation}. Consider just passing key explicitly - e.g. docs.py (path, citation, key='mykey')"
                )
        ...
        key += suffix
        self.keys.add(key)
        ...
            raise ValueError(
                f"This does not look like a text document: {path}. Path disable_check to ignore this error."
            )
        ...
        self.docs[path] = dict(texts=texts, metadata=metadata, key=key)
        if self._faiss_index is not None:
            self._faiss_index.add_texts(texts, metadatas=metadata)
        if self._doc_index is not None:
            self._doc_index.add_texts([citation], metadatas=[{"key": key}])
```

This means if you skip over items with `try-except`, it could occur that the `self.keys` object had already been updated. Or, perhaps the `keys` and `docs` are updated, but something errors in the `_faiss_index`.

#### Solution:

Only update the `self.keys`, `self.docs`, and `self._faiss_index`, at the very end of the method. All errors should be raised before that point (i.e., manually check whether `key` is in `self.keys` beforehand). Also, `self._faiss_index.add_texts` should be ran before `self.keys` and `self.docs` are updated.

**Comment by whitead** [comment]
Fixed in #53
