### ISSUE TITLE
Have cheaper mode

### ISSUE THREAD

**Issue by whitead** [whitead/paper-qa#7]
Perhaps using `curie` or `sentence-transformer` for embeddings (relatively cheap anyway). Distillbert might be good too.

https://huggingface.co/deepset/deberta-v3-large-squad2

**Comment by tiwentichat** [comment]
excuse me sir, i met a question on huggingface project you made.

Error like this:

This does not look like a text document: /tmp/requirementfyo6931m.txt. Path disable_check to ignore this error.

I draged a txt, input the apikey, then ask question below, the error came out.

actually, it's txt, why, what's wrong?

May you help me?

Thanks

**Comment by whitead** [comment]
@tiwentichat should be fixed

**Comment by liusok** [comment]
> 

I also have this issue.

**Comment by liusok** [comment]
> 

Hi, whitead. I got this message: "This model's maximum context length is 8191 tokens, however you requested 19149 tokens (19149 in your prompt; 0 for the completion). Please reduce your prompt; or completion length." I only ask a question with 10 words. How to fix it?

**Comment by tiwentichat** [comment]
> @tiwentichat should be fixed

yes，great！

**Comment by whitead** [comment]
@liusok try latest version - had this problem too yesterday

**Comment by whitead** [comment]
Got cheaper mode now
