### ISSUE TITLE
Method for adding PDFs to Docs from webpage link

### ISSUE THREAD

**Issue by malekinho8** [whitead/paper-qa#72]
It would be nice to be able to pass a webpage link to a PDF in order to begin the query process. The method should fetch the PDF from the provided URL and then save it to a temporary file which can then be added as normal.

**Comment by Mason-McGough** [comment]
Working on a solution to this: https://github.com/whitead/paper-qa/pull/133

**Comment by whitead** [comment]
Added in v3
