### ISSUE TITLE
Longer answers than 150 words

### ISSUE THREAD

**Issue by goldengrape** [whitead/paper-qa#77]
https://github.com/whitead/paper-qa/blob/93c47ccc7ea496a1167ac2b89e7fa512dee7be7f/paperqa/qaprompts.py#L16

"Use 150 or less words."

Is it possible to set "150" as a variable? It is possible that we need a more detailed and longer answer

**Comment by whitead** [comment]
Yes, there is an interaction between maximum sources, model context length, summarization length, and chunking size. Certainly can make it another variable, but need to think about ensuring all of these fit correctly.

**Comment by whitead** [comment]
This is now possible in v3, by editing the prompt templates. The maximum length is now also automatically computed.
