### ISSUE TITLE
'paperqa' has no attribute 'run_agent'

### ISSUE THREAD

**Issue by gurugecl** [whitead/paper-qa#86]
I am trying to run the example code using agents:

docs = paperqa.Docs()
answer = paperqa.run_agent(docs, 'What compounds target AKT1')
print(answer)

But getting the following error:
AttributeError: module 'paperqa' has no attribute 'run_agent'

Using version 1.1.1

**Comment by whitead** [comment]
Not sure - should be working. Unit tests use this

**Comment by gurugecl** [comment]
Oh ok. Yeah it's weird. When I print the attributes even with version 1.4.0 these are the only attributes available:

['Answer', 'Docs', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'docs', 'maybe_is_text', 'qaprompts', 'readers', 'utils', 'version']
