### ISSUE TITLE
Basic example not working on Windows

### ISSUE THREAD

**Issue by Chubop** [whitead/paper-qa#88]
```
from paperqa import Docs

docs = Docs()
docs.add('transcripts/lpsn_transcript.txt')


answer = docs.query("What is LivePerson?")
print(answer.formatted_answer)
```

Very basic example only using one text file returns this error. Text file is ~55,000 words long.

`ValueError: Number of columns in X and Y must be the same.`

**Comment by whitead** [comment]
See https://github.com/whitead/paper-qa/issues/79
